Amend MOJ Asylum finder
alphagov/specialist-publisher pull request #927
Opened 2016-10-24 16:49 UTC by lgarvey

Amend the asylum finder category and sub category to allow multiple
types

2016-10-24 18:58 UTC, tijmenb commented
The way we do contract testing limits our ability to change the type of attributes in content items. 
Because schemas have to be backwards compatible, a test for a content schema change won't pass in CI. And without that change this PR won't pass in CI.

Also, I suspect that changing the type might cause problems in either elasticsearch or in the app itself.
 
I think the best thing to do here is to add `tribunal_decision_categories` and `tribunal_decision_sub_categories` attribute to the content schemas and rummager. This has the added benefit of having the correct pluralized name.

We can optionally copy over the current values in a rake task if we want to maintain the data (there are 83 `asylum_support_decision` documents).

I suspect that the same change has to be done for the Tax Tribunal decisions?

2016-10-25 18:35 UTC, lgarvey commented
That makes sense.

We haven't done any work with tax tribunals - so it's unlikely to need
amending.

On 24 October 2016 at 19:58, Tijmen Brommet <notifications@github.com>
wrote:

> The way we do contract testing limits our ability to change the type of
> attributes in content items.
> Because schemas have to be backwards compatible, a test for a content
> schema change won't pass in CI. And without that change this PR won't pass
> in CI.
>
> Also, I suspect that changing the type might cause problems in either
> elasticsearch or in the app itself.
>
> I think the best thing to do here is to add tribunal_decision_categories
> and tribunal_decision_sub_categories attribute to the content schemas and
> rummager. This has the added benefit of having the correct pluralized name.
>
> We can optionally copy over the current values in a rake task if we want
> to maintain the data (there are 83 asylum_support_decision documents).
>
> I suspect that the same change has to be done for the Tax Tribunal
> decisions?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alphagov/specialist-publisher/pull/927#issuecomment-255832711>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOhY5MkGUr3sLlxqKzraK4ZVFIhC9y9ks5q3P_AgaJpZM4KfBgX>
> .
>

2016-11-02 18:34 UTC, tijmenb requested changes
This looks good. Can you squash the commits together?

2016-11-02 18:34 UTC, tijmenb commented on app/models/asylum_support_decision.rb
> +      tribunal_decision_categories
If you keep this `tribunal_decision_category` and `tribunal_decision_sub_category` here temporarily, we can use it for the migration.

2016-11-04 16:57 UTC, tijmenb approved these changes

2016-11-04 17:46 UTC, lgarvey commented
@tijmenb don't merge this yet. I see a missing sub category field in
the FORMAT_SPECIFIC_FIELDS
array. Will fix on Monday.

On 4 November 2016 at 16:57, Tijmen Brommet <notifications@github.com>
wrote:

> *@tijmenb* approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alphagov/specialist-publisher/pull/927#pullrequestreview-7241721>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOhY6wEPqi16pcgeTjvKec9hYBujFceks5q62P0gaJpZM4KfBgX>
> .
>

2016-11-07 15:41 UTC, lgarvey commented
@tijmenb I've added back in the missing tribunal_decision_sub_categories field, so this looks good to merge now.

2016-11-07 19:18 UTC, merged

2016-11-09 12:53 UTC, tijmenb commented on app/views/metadata_fields/_asylum_support_decisions.html.erb
>    <%= f.select :tribunal_decision_category,
This needs to read `:tribunal_decision_categories`.

2016-11-09 12:54 UTC, tijmenb commented on app/views/metadata_fields/_asylum_support_decisions.html.erb
> +             placeholder: 'Select judges'
This should probably be "Select categories"

2016-11-09 12:54 UTC, tijmenb commented on app/views/metadata_fields/_asylum_support_decisions.html.erb
> +             placeholder: 'Select judges'
Same here.

2016-11-09 12:55 UTC, tijmenb commented
For this PR to work we also need to change

https://github.com/alphagov/specialist-publisher/blob/master/lib/documents/schemas/asylum_support_decisions.json#L49

and

https://github.com/alphagov/specialist-publisher/blob/master/lib/documents/schemas/asylum_support_decisions.json#L71

That way the dropdown will be populated.