Test finder schemas match specialist document schema
alphagov/specialist-publisher pull request #961
Opened 2016-12-06 11:51 UTC by Davidslv

Move the FinderSchemaConverter class from govuk-content-schemas.
We used to have a script there that generated the `metadata` part
of the `specialist_document` content schema, based on the finder
schemas published by specialist publisher:
https://github.com/alphagov/govuk-content-schemas/blob/66b11b4004b49064b6aae16715158740977dc706/bin/convert_finder_schemas

This was a bit out of date, and didn't work with all the schemas we've
created. We've changed this to a set of tests in specialist publisher,
so that consistency is always checked for new schemas, unless they are
explicitly added to the `IGNORED_FINDERS` array.

Trello: https://trello.com/c/lFZnNhs4/349-create-a-service-assessment-finder
Paired with @klssmith @MatMoore

2016-12-06 12:18 UTC, tijmenb requested changes
Cool, very useful! `FinderSchemaConverter` has a lot of responsibilities though, perhaps it could be refactored a little.

2016-12-06 12:18 UTC, tijmenb commented on spec/lib/schema_consistency_spec.rb
> +    FinderSchemaConverter.except_ignored_finders.each do |finder_schema|
The selection, looping and reading of the finders to test could be moved into here to make `FinderSchemaConverter` do less. You could instantiate the `FinderSchema` in here.

2016-12-06 12:18 UTC, tijmenb commented on lib/finder_schema_converter.rb
> +  MULTI_SELECTS_BY_DOCUMENT_TYPE = {
Would it be possible to get this data from the schemas?

2016-12-08 10:00 UTC, Davidslv commented on lib/finder_schema_converter.rb
> +  MULTI_SELECTS_BY_DOCUMENT_TYPE = {
There might be, but I'm not sure how would we go about it.

2016-12-08 11:00 UTC, MatMoore commented on spec/lib/schema_consistency_spec.rb
> +    FinderSchemaConverter.except_ignored_finders.each do |finder_schema|
Yeah that sounds reasonable, since the test is the only thing making use of it, and it would make it a bit more obvious what's being excluded.

2016-12-13 16:11 UTC, Davidslv commented
I think we should close this for the moment being?

2016-12-13 16:44 UTC, tijmenb commented
@Davidslv yeah, seems sensible. Let's revisit once the finder has been shipped.

2016-12-13 16:46 UTC, Davidslv commented
Thanks

2016-12-13 16:46 UTC, closed without merging