Add assessment_date for Service Standard Report
alphagov/specialist-publisher pull request #970
Opened 2016-12-14 16:46 UTC by Davidslv

This depends on https://github.com/alphagov/govuk-content-schemas/pull/462 to be merged first in order for the test suite to be green.

We are adding `assessment_date` as part of the metadata sent to
Publishing API. This means that editors will be able to set the date of a given assessment.

This is a follow up work on moving all the service assessments and self
certification documents away from GDS Data blog
(https://gdsdata.blog.gov.uk/all-service-assessments-and-self-certification/)
and move them to Specialist Publisher.

Trello:
https://trello.com/c/ADPnDXsE/385-add-assessment-date-to-service-standard-specialist-document

Paired with: @klssmith

2016-12-14 17:31 UTC, tijmenb requested changes
Looks good, apart from the requiredness. If we make the attribute required at the moment we won't be able to import data -- it's something the editors have to set manually.

2016-12-14 17:31 UTC, tijmenb commented on app/models/service_standard_report.rb
> +  validates :assessment_date, presence: true
I thought we talked about this not being required?

2016-12-15 11:06 UTC, Davidslv commented
@tijmenb I've updated this PR to not validate `assessment_date`.
Thanks

2016-12-15 11:37 UTC, tijmenb approved these changes

2016-12-15 11:37 UTC, tijmenb commented
Cool. Good to merge after content schemas and rummager is updated.

2016-12-15 12:41 UTC, merged