[WIP] Provide rake task to generate report for Content Operating Model team
alphagov/specialist-publisher pull request #981
Opened 2017-01-05 16:31 UTC by h-lame

The report is to show the organisation(s), url, finder, status and
first published date for all the documents in the system.

We expect that this is a one-off, but it might be useful for the code
that generates it to persist as this kind of report could be needed
again, or could be used as a jumping off point for future reports.

The trello card describing the report is: https://trello.com/c/e3nDUdE2/88-report-for-content-operating-model

2017-01-05 16:32 UTC, h-lame commented
Marked as WIP because we've some outstanding questions about what exactly is needed in the report.

2017-01-17 12:52 UTC, h-lame commented
Removed WIP tag as we've checked with the requestor that these reports provide them what they need.

2017-01-18 16:44 UTC, NeilvB commented on lib/tasks/report.rake
> +        "publication_state" => finder_document["publication_state"],
Might it be useful to have a fallback value here too?

2017-01-18 16:44 UTC, NeilvB commented
Overall looks good 👍

2017-01-18 16:51 UTC, h-lame commented on lib/tasks/report.rake
> +        "publication_state" => finder_document["publication_state"],
Oh yeah, good point.  Will do.

2017-01-19 10:29 UTC, neilvanbeinum requested changes

2017-01-19 10:29 UTC, NeilvB commented on lib/tasks/report.rake
> +              document_hash["publication_state"],
We should probably have a fallback value here too

2017-01-19 13:52 UTC, h-lame commented on lib/tasks/report.rake
> +              document_hash["publication_state"],
I don't think it's possible for a document in the publishing api to not have a state. Unlike first published at which can be blank for documents that haven't been published.

2017-01-19 13:54 UTC, neilvanbeinum approved these changes

2017-01-19 13:59 UTC, merged