Correct MOJ UTAAC finder title
alphagov/specialist-publisher pull request #993
Opened 2017-01-30 12:05 UTC by lgarvey

2017-01-30 14:53 UTC, tomwm commented on lib/documents/schemas/utaac_decisions.json
> +  "summary": "<p>Find decisions on appeals to the Upper Tribunal (Administrative Appeals Chamber), including social security and child support appeals.</p><p>Includes decisions after December 2015. F
http://www.osscsc.gov.uk/Aspx/default.aspx\ actually redirects to http://administrativeappeals.decisions.tribunals.gov.uk/Aspx/default.aspx

So we should probably just have the later.

2017-02-01 16:12 UTC, sihugh requested changes
Hi, just a comment on the summary text after we had a content review.

2017-02-01 16:12 UTC, sihugh commented on lib/documents/schemas/utaac_decisions.json
> +  "summary": "<p>Find decisions on appeals to the Upper Tribunal (Administrative Appeals Chamber), including social security and child support appeals.</p><p>Includes decisions after December 2015. F
Jon Sanger had a look at this and suggested that the second `<p>` might read a little better and be more accessible if we tweaked it to:

`<p>This includes decisions made from January 2016 onwards. You can find details of <a rel=\"external\" href=\"http://administrativeappeals.decisions.tribunals.gov.uk/Aspx/default.aspx\">decisions made in 2015 or earlier</a> on the Courts and Tribunals Judiciary website.</p>`

2017-02-01 16:20 UTC, tomwm commented on lib/documents/schemas/utaac_decisions.json
> +  "summary": "<p>Find decisions on appeals to the Upper Tribunal (Administrative Appeals Chamber), including social security and child support appeals.</p><p>Includes decisions after December 2015. F
Yes, thats a good build, i'm happy with that.

2017-02-02 10:30 UTC, lgarvey commented
@sihugh I've amended the text

2017-02-02 10:32 UTC, sihugh commented
Thanks!

2017-02-02 10:32 UTC, merged