[Review only] Add content store document type attribute for search
alphagov/specialist-publisher pull request #996
Opened 2017-02-02 15:24 UTC by Davidslv

Add `content_store_document_type` to be sent to rummager.

Also, currently we have in place a task to republish documents to Publishing API and
Rummager, but in some cases we only want to republish to rummager in
order to update the document.

This commit adds an extra task into the republish.rake file to republish
all documents to rummager.

And also adds `content_id`, `rendering_app` and `publishing_app`

This might be best to be reviewed commit by commit (will rebase afterwards)

Trello:
https://trello.com/c/iMotNdUv/461-add-more-document-type-to-search

2017-02-02 15:39 UTC, Davidslv commented
This needs more testing but I wanted to know your opinion on the implementation first.

2017-02-02 17:20 UTC, tijmenb requested changes
As discussed on Slack, there's a sizeable chunk of copy-pasted code that isn't necessary for what we're trying to achieve.

2017-02-02 17:20 UTC, tijmenb commented on lib/rummager_republisher.rb
> +      while pagination[:current_page] <= pagination[:total_pages]
I don't get what's going on here. 

`pagination[:current_page]` is not being mutated, and the inside of this block is  always the same?

2017-02-03 14:43 UTC, Davidslv commented
@tijmenb I believe I've addressed your comments. Let me know your thoughts.

2017-02-07 16:08 UTC, closed without merging

2017-02-07 16:18 UTC, Davidslv commented
We think this work might have caused problems after running on Integration and we have decided to run the original republish.rake task